//
//  ViewController.swift
//  Hello_SpeechRecognition
//
//  Created by Cyril Garcia on 6/20/19.
//  Copyright © 2019 Cyril Garcia. All rights reserved.
//

import UIKit
import Speech

class ViewController: UIViewController, SFSpeechRecognizerDelegate {
    
    @IBOutlet var detectedTextLabel: UILabel!
    @IBOutlet var startListingButton: UIButton!
    
    private var speechRecognizer: SpeechRecognizerModel!
    private var textClassification: TextClassificationModel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        speechRecognizer = SpeechRecognizerModel()
        speechRecognizer.requestSpeechAuthorization { (success) in
            print(success)
        }
        
        textClassification = TextClassificationModel()
    }
    
    @IBAction func startListening() {
        
        speechRecognizer.classifySpeech { (recognizedSpeech, error) in
            self.startListingButton.isEnabled = false
            if let recognizedSpeech = recognizedSpeech {
                self.detectedTextLabel.text = recognizedSpeech
                //                let results = self.textClassification.classify(text: recognizedSpeech)
                //                print(recognizedSpeech, "->",results)
            }
            
            
            
        }
    }
    
    @IBAction func restart() {
        self.startListingButton.isEnabled = true
        self.speechRecognizer.finishRecognitionTask()
    }
    
    @IBAction func classifyText() {
        let x = ["yes",
                 "Yas",
                 "Yep",
                 "Yup",
                 "Yas",
                 "Totally",
                 "Totes",
                 "Sure",
                 "You bet",
                 "Okay",
                 "K",
                 "Kay",
                 "Ok ",
                 "Okie dokie",
                 "Alright",
                 "Alrighty",
                 "Sounds good",
                 "For sure",
                 "Sure thing",
                 "Certainly",
                 "Absolutely",
                 "Indeed",
                 "Undoubtedly",
                 "Fine",
                 "Affirmative",
                 "Very well",
                 "Yea",
                 "Mhmm",
                 "Uh-huh",
                 "Nah ",
                 "Nope",
                 "No way",
                 "Not now",
                 "Certainly not",
                 "By no means",
                 "I shall not",
                 "Not likely",
                 "No thanks",
                 "I think not",
                 "Unfortunately not",
                 "Im slammed",
                 "Not possible",
                 "Not this time",
                 "Not for me thanks",
                 "I think I’ll pass",
                 "Pass",
                 "Next time",
                 "Maybe another time",
                 "Not interested",
                 "No thank you",
                 "Not sure",
                 "I don’t want to",
                 "Please no",
                 "Not right now",
                 "not for now",
                 "No",
                 "Don’t",
                 "Sorry",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I agree",
                 "I’m sure",
                 "I’m sure",
                 "I’m sure",
                 "I’m sure",
                 "I’m sure",
                 "Aye",
                 "Cary on",
                 "Do it",
                 "Do it",
                 "Do it",
                 "get on with it then",
                 "go ahead",
                 "i agree",
                 "make it happen",
                 "make it so",
                 "most assuredly",
                 "perfect, thanks",
                 "please do",
                 "Rock on",
                 "that's correct",
                 "that's right",
                 "uh huh",
                 "yes, please",
                 "yes, please",
                 "yes, please",
                 "you got it",
                 "absolutely",
                 "absolutely",
                 "affirmative",
                 "alright",
                 "assuredly",
                 "aye",
                 "certainly",
                 "confirmed",
                 "continue",
                 "continue",
                 "correct",
                 "da",
                 "good",
                 "hooray",
                 "ja",
                 "ok",
                 "ok",
                 "ok",
                 "okay",
                 "proceed",
                 "righto",
                 "sure",
                 "sure",
                 "sure",
                 "sure",
                 "sure",
                 "sure",
                 "sure",
                 "sure",
                 "sure",
                 "thanks",
                 "totally",
                 "TRUE",
                 "y",
                 "ya",
                 "ya",
                 "yay",
                 "yea",
                 "yeah",
                 "yeah",
                 "yep",
                 "yeppers",
                 "yes",
                 "yes",
                 "cancel",
                 "denied",
                 "disengage",
                 "don't",
                 "end",
                 "exit",
                 "halt",
                 "n",
                 "nah",
                 "nay",
                 "nay",
                 "neg",
                 "negative",
                 "negatory",
                 "nein",
                 "nevermind",
                 "nevermind",
                 "no",
                 "no",
                 "no",
                 "nope",
                 "nope",
                 "nyet",
                 "quit",
                 "skip",
                 "stop",
                 "stop",
                 "I changed my mind",
                 "I don't agree",
                 "I don't agree",
                 "I don't agree",
                 "I don't agree",
                 "I don't agree",
                 "absolutely not",
                 "belay that",
                 "cut it out",
                 "don't do anything",
                 "don't do it",
                 "forget it",
                 "never mind",
                 "no thanks",
                 "no way",
                 "on second thought, don't do it",
                 "please don't",
                 "scratch that"]
        
        let y = [1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 1,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0]
        
        for i in 0..<x.count {
            let res = self.textClassification.classify(text: x[i])!
            if res != (y[i] == 1) {
                print("text",x[i], "true_label", y[i] == 1, "predicted",res)
            }
        }
        
    }
    
    @IBAction func clearLabel() {
        detectedTextLabel.text = ""
    }
    
}

